---
abstract: 'Loading essential Perl Moose modules.'
author:
  - "Jue\x81rgen von Brietzke <juergen.von.brietzke@t-online.de>"
build_requires:
  Test::More: '0'
  Test::Perl::Critic: '0'
  Test::Pod: '1.14'
  Test::Pod::Coverage: '1.04'
configure_requires:
  Module::Build: '0.42'
dynamic_config: 1
generated_by: 'Module::Build version 0.4214, CPAN::Meta::Converter version 2.150005'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Perl-Modern-Moose
provides:
  Perl::Modern::Moose:
    file: lib/Perl/Modern/Moose.pm
    version: '1.004'
requires:
  English: '0'
  Hook::AfterRuntime: '0'
  Moose: '0'
  Moose::Exporter: '0'
  Moose::Util::TypeConstraints: '0'
  MooseX::AttributeShortcuts: '0'
  MooseX::Declare: '0'
  MooseX::DeclareX: '0'
  MooseX::DeclareX::Privacy: '0'
  MooseX::HasDefaults::RO: '0'
  namespace::autoclean: '0'
  version: '0'
version: '1.004'
x_serialization_backend: 'CPAN::Meta::YAML version 0.016'
